[[session]]
name = "Downloads ⬇️"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Music 🎼"
path = "~/Music"
startup_command = "cmus"

[[session]]
name = "Dev ⌨️"
path = "~/src"
startup_command = "nvim +GoToFile"

[[session]]
name = "Youtube 📺"
path = "~/Videos"
startup_command = "yt-x"

[[session]]
name = "Cloud ☁️"
path = "~/Documents/Main/baks/selfhosting"
startup_command = "pod-up"

[[session]]
name = "Notes 📝"
path = "~/Documents/Main"
startup_command = "nvim +GoToFile"
